version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"

  txoco:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: /bin/sh
    depends_on:
      - ganache